version: "3.8"
services:
  web:
    image: "node:16"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    working_dir: /home/web
    volumes:
      - .:/home/web
    command: "npm run dev"
