import type { NextPage } from "next"
import Head from "next/head"
import { getEntry } from "services/contentful/client/util/getEntry"
import { PageModel } from "services/contentful/models/page/page.types"
import { Entry } from "contentful"

export interface NextPageModel {
  page?: Entry<PageModel>
}

const Page: NextPage<NextPageModel> = (props) => {
  return (
    <div>
      <Head>
        <title>{props.page?.fields.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{props.page?.fields.title}</main>
    </div>
  )
}

Page.getInitialProps = async (context) => {
  const page = await getEntry<PageModel>({
    "content_type": "page",
    "fields.slug": context.query.slug,
    "include": 10
  })

  return {
    page
  }
}

export default Page
